name: Generate BattleScribe Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.cat'
      - '**.gst'
      - '**.catz'
      - '**.gstz'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        # Prepara el entorno .NET necesario para la herramienta

      - name: Install wham CLI
        run: dotnet tool install --global wham
        # Instala la herramienta oficial de la comunidad BattleScribe

      - name: Generate Index
        run: wham index ./
        # Escanea la carpeta y genera el index.bsi

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.bsi
          git diff --quiet && git diff --staged --quiet || (git commit -m "Release: Auto-generando index.bsi" && git push)
