name: Generate BattleScribe Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.cat'
      - '**.gst'
      - '**.catz'
      - '**.gstz'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # <--- Esto elimina la advertencia

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install bsdata-cli
        run: npm install -g bsdata-cli

      - name: Generate Index
        run: bsdata index ./

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.bsi
          git diff --quiet && git diff --staged --quiet || (git commit -m "Release: Actualización automática del índice" && git push)
